server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LichKing-lee/spring-cloud-config-2.4-example.git
          private-key: |

          search-paths: property